name: Build and Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g. latest, v0.62.0)'
        required: true
        default: 'latest'

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build Docker Images and Binaries
    runs-on: ubuntu-latest
    steps:
      # environment
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - uses: actions/setup-node@v6
        with:
          node-version: '22'

      # get image tag name
      - name: Get Image Tag Name
        run: |
          echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: xiaozhu245
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      # build Docker images
      - name: Build and push frpc
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./dockerfiles/Dockerfile-for-frpc
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            registry.cn-beijing.aliyuncs.com/xiaozhu245/frp_auto:frpc-${{ env.TAG_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frps
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./dockerfiles/Dockerfile-for-frps
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            registry.cn-beijing.aliyuncs.com/xiaozhu245/frp_auto:frps-${{ env.TAG_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # build binaries
      - name: Build web assets
        run: |
          make -C web/frps build
          make -C web/frpc build

      - name: Build frpc binary
        run: |
          go build -trimpath -ldflags "-s -w" -tags "frpc" -o bin/frpc ./cmd/frpc

      - name: Build frps binary
        run: |
          go build -trimpath -ldflags "-s -w" -tags "frps" -o bin/frps ./cmd/frps

      - name: Upload frpc binary
        uses: actions/upload-artifact@v4
        with:
          name: frpc-linux-amd64
          path: bin/frpc

      - name: Upload frps binary
        uses: actions/upload-artifact@v4
        with:
          name: frps-linux-amd64
          path: bin/frps
